---
- name: "Lua | Update APT cache"
  apt:
    update_cache: true
  become: true
  changed_when: false

- name: "Lua | Install Lua"
  ansible.builtin.apt:
    name:
      - lua5.3
      - luarocks
      - luajit
    state: latest
  become: true

- name: "Lua | Gather installed lua rocks"
  ansible.builtin.command: luarocks list
  register: rocks
  changed_when: false
  check_mode: false
