---
- name: Lua | Install Lua
  ansible.builtin.apt:
    name:
      - lua5.3
      - luarocks
      - luajit
    state: present
    update_cache: true
  become: true

- name: Lua | Gather installed lua rocks
  ansible.builtin.command: luarocks list
  register: rocks
  changed_when: false
  check_mode: false
