---
- name: "Bash | Copy .bashrc"
  ansible.builtin.copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir }}/dev_env/.bashrc"
    mode: "0644"

- name: "Bash | Copy .bash_profile"
  ansible.builtin.copy:
    src: ".bash_profile"
    dest: "{{ ansible_user_dir }}/dev_env/.bash_profile"
    mode: "0644"

- name: "Bash | Copy custom bash config"
  ansible.builtin.copy:
    src: "bash"
    dest: "{{ ansible_user_dir }}/dev_env/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true

- name: "Bash | Set default terminal"
  user:
    name: "{{ host_user }}"
    shell: "/usr/bin/bash"
  become: true

- name: "Bash | Set public variables"
  ansible.builtin.template:
    src: ".bash_public.j2"
    dest: "{{ ansible_user_dir }}/dev_env/.config/bash/.bash_public"
    mode: "0644"

- name: "Bash | Set private variables"
  ansible.builtin.template:
    src: ".bash_private.j2"
    dest: "{{ ansible_user_dir }}/dev_env/.config/bash/.bash_private"
    mode: "0644"
  no_log: true
