---
- name: Bash | Create symlink to .bashrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    state: link
    force: true
  become: true

- name: Bash | Create symlink to .bash_profile
  ansible.builtin.file:
    src: "{{ role_path }}/files/.bash_profile"
    dest: "{{ ansible_user_dir }}/.bash_profile"
    state: link
    force: true
  become: true

- name: Bash | Create symlink to .inputrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/.inputrc"
    dest: "{{ ansible_user_dir }}/.inputrc"
    state: link
    force: true
  become: true

- name: Bash | Create symlink to .dircolors
  ansible.builtin.file:
    src: "{{ role_path }}/files/.dircolors"
    dest: "{{ ansible_user_dir }}/.dircolors"
    state: link
    force: true
  become: true

- name: Bash | Copy custom bash config
  ansible.builtin.copy:
    src: bash
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true
  become: true

- name: Bash | Set default terminal
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /usr/bin/bash
  become: true

- name: Bash | Set public variables
  ansible.builtin.template:
    src: .bash_public.j2
    dest: "{{ ansible_user_dir }}/.config/bash/.bash_public"
    mode: "0644"
  become: true

- name: Bash | Set private variables
  ansible.builtin.template:
    src: .bash_private.j2
    dest: "{{ ansible_user_dir }}/.config/bash/.bash_private"
    mode: "0644"
  no_log: true
  become: true

- name: Bash | Setup work environment
  when: work_env is defined
  become: true
  block:
    - name : Bash | Work | Ensure work config directory exists
      ansible.builtin.file:
          path: "{{ ansible_user_dir }}/.config/bash/work/"
          state: directory
          mode: "0755"
      register: work_config_dir

    - name: Bash | Work | Set public variables
      ansible.builtin.template:
        src: .work_public.j2
        dest: "{{ work_config_dir.path }}/.work_public"
        mode: "0644"

    - name: Bash | Work | Set private variables
      ansible.builtin.template:
        src: .work_private.j2
        dest: "{{ work_config_dir.path }}/.work_private"
        mode: "0644"
      no_log: true

    - name: Bash | Work | Copy custom work config
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ work_config_dir.path }}"
        mode: "0644"
        directory_mode: "0755"
        force: true
      with_fileglob:
        - "work/*"
      loop_control:
        label: "{{ item }}"
      become: true
