---
- name: System | Ubuntu | Update APT Repos and Upgrade APT Packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    state: latest
    autoremove: true
    autoclean: true
    only_upgrade: true
  become: true
  changed_when: false
  failed_when: false

- name: System | Ubuntu | Install
  ansible.builtin.apt:
    name:
      - jq
      - open-iscsi
      - autojump
      - aptitude
      - fd-find
    state: present
  become: true
