---
- name: Regolith | Add GPG key
  ansible.builtin.apt_key:
    url: https://archive.regolith-desktop.com/regolith.key
    keyring: /usr/share/keyrings/regolith-archive-keyring.gpg
    state: present
  become: true

- name: Regolith | Get System Architecture
  ansible.builtin.command: dpkg --print-architecture
  register: regolith_dpkg_architecture
  changed_when: false
  failed_when: false
  check_mode: false

- name: Regolith | Add Regolith’s stable repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ regolith_dpkg_architecture.stdout }} signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg]
      https://archive.regolith-desktop.com/{{ ansible_distribution | lower }}/stable {{ ansible_distribution_release }} v3.3
    state: present
    filename: regolith
  become: true

- name: Regolith | Update apt package cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Regolith | Install Regolith desktop
  ansible.builtin.apt:
    name:
      - regolith-desktop
      - regolith-session-flashback
      - regolith-look-lascaille
      - i3xrocks-app-launcher
      - i3xrocks-battery
      - i3xrocks-focused-window-name
      - i3xrocks-info
      - i3xrocks-volume
      - dunst
      - libnotify-bin
    state: present
  become: true
