---
- name: "Flatpak | Install flatpak"
  ansible.builtin.apt:
    name: flatpak
    state: present
    update_cache: true
  become: true

- name: "Flatpak | Add Flathub remote"
  community.general.flatpak_remote:
    name: "flathub"
    flatpakrepo_url: "https://flathub.org/repo/flathub.flatpakrepo"
    state: present
  become: true
