---
- name: Brave | Add GPG key
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'
    force: true
  become: true

- name: Brave | Add Brave repository
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser.sources
    dest: /etc/apt/sources.list.d/brave-browser-release.sources
    mode: '0644'
    force: true
  become: true

- name: Brave | Update apt package cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Brave | Install Brave browser
  ansible.builtin.apt:
    name: brave-browser
    state: present
  become: true
