---
- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Git | Set global configs
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - name: init.defaultBranch
      value: master
    - name: fetch.prune
      value: true
    - name: pull.rebase
      value: true
    - name: rebase.autoStash
      value: true
    - name: user.email
      value: "{{ git_user_email }}"
    - name: user.name
      value: "{{ git_user_name }}"
    - name: core.editor
      value: nvim
    - name: alias.co
      value: checkout
    - name: alias.uncommit
      value: reset HEAD^
    - name: alias.last
      value: log -1 HEAD
    - name: alias.pop
      value: stash pop
    - name: alias.del
      value: branch -D
    - name: alias.lg
      value: log --graph --pretty=format:'%C(yellow)%d%Creset %C(cyan)%h%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=short --all
    - name: alias.rename
      value: branch -m
