---
- name: "Tmux | Install Tmux"
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true

- name: "Tmux | Install TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"

- name: "Tmux | Create symlink to Tmux config"
  ansible.builtin.file:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_user_dir }}/.tmux.conf"
    state: link
    force: true
  become: true
