---
- name: "Pyenv | Install dependencies"
  ansible.builtin.apt:
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libffi-dev
      - liblzma-dev
      - python-openssl
    state: present
  become: true

- name: "Pyenv | Check if pyenv is installed"
  ansible.builtin.command: "which pyenv"
  register: pyenv_check
  changed_when: false

- name: "Pyenv | Install"
  when: pyenv_check.rc != 0
  block:
    - name: "Pyenv | Download Pyenv installer"
      ansible.builtin.get_url:
        url: "https://pyenv.run"
        dest: "/tmp/pyenv-installer"
        mode: "0755"
      notify: "Pyenv | Cleanup pyenv installer"

    - name: "Pyenv | Run Pyenv installer"
      ansible.builtin.shell: "/tmp/pyenv-installer"
      args:
        creates: "{{ ansible_user_dir }}/.pyenv"
      become: true

    - name: "Pyenv | Source .bashrc"
      ansible.builtin.shell: exec "$SHELL"
      args:
        executable: "/bin/bash"
      changed_when: false
  become: true


- name: "Pyenv | Install Python versions"
  ansible.builtin.shell: "pyenv install -sv {{ item }}"
  args:
    executable: "/bin/bash"
  loop:
    - "3.10.13"
    - "3.8.18"
  become: true
  changed_when: false

- name: "Pyenv | Set global Python version"
  ansible.builtin.shell: "pyenv global 3.10.13"
  args:
    executable: "/bin/bash"
  become: true
  changed_when: false
