---
- name: "Neofetch | Install neofetch"
  ansible.builtin.apt:
    name: neofetch
    state: latest
  become: true

- name: "Neofetch | Ensure .config directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/neofetch"
    state: directory
    mode: "0755"

- name: "Neofetch | {{ ansible_distribution }} | Copy config file"
  ansible.builtin.copy:
    src: config.conf
    dest: "{{ ansible_user_dir }}/.config/neofetch/config.conf"
    mode: "0644"
