---
- name: Neovim | Install dependencies
  ansible.builtin.package:
    name:
      - cmake
      - pkg-config
      - libtool
      - curl
      - unzip
      - ripgrep
      - software-properties-common
    state: present
    update_cache: true
  become: true

- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'

- name: Neovim | Create symlink to role files directory
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true

- name: Neovim | Setup formatters and linters
  block:
    - name: Neovim | Install Node.js dependencies
      community.general.npm:
        name: npm-groovy-lint
        global: true
        state: present
      become: true

    - name: Neovim | Install Cargo dependencies
      community.general.cargo:
        name: rustfmt
        state: present
