---
- name: Neovim | Ubuntu | Remove snap install if present
  community.general.snap:
    name: nvim
    state: absent
  become: true
  ignore_errors: true

- name: Neovim | Ubuntu | Add nightly PPA
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present
    update_cache: true
  become: true

- name: Neovim | Ubuntu | Install
  ansible.builtin.package:
    name: neovim
    state: present
  become: true
