---
- name: "Neovim | Install dependencies"
  ansible.builtin.package:
    name:
      - cmake
      - pkg-config
      - libtool
      - ansible-lint
      - curl
      - unzip
      - ripgrep
    state: latest
  become: true

- name: "Neovim | Install"
  community.general.snap:
    name: nvim
    classic: true
  become: true

- name: "Neovim | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/nvim"
    state: link
    force: true
