---
- name: Bat | Download latest version JSON
  ansible.builtin.uri:
    url: https://api.github.com/repos/{{ bat_gh_user }}/{{ bat_gh_repo }}/releases/latest
  register: bat_latest_version_json
  changed_when: false
  when: bat_target_bat_version|length == 0

- name: Bat | Registering bat latest release
  ansible.builtin.set_fact:
    bat_latest_release: "{{ bat_latest_version_json.json.tag_name }}"
  when: bat_target_bat_version|length == 0

- name: Bat | Set latest version of bat
  ansible.builtin.set_fact:
    bat_target_bat_version: "{{ bat_latest_release.stdout | default('') }}"
  when: bat_target_bat_version|length == 0

- name: Bat | Getting local version information
  ansible.builtin.command: bat -V
  register: bat_current_version
  changed_when: false
  failed_when: false

- name: Bat | Show bat_current_version debug
  ansible.builtin.debug:
    var: bat_current_version.stdout|default('')

- name: Bat | Show bat_target_bat_version debug
  ansible.builtin.debug:
    var: bat_target_bat_version|default('')

- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
