---
- name: "Fonts | Update APT cache"
  ansible.builtin.apt:
    update_cache: true
  become: true
  changed_when: false

- name: "Fonts | Install fontconfig and emoji support"
  ansible.builtin.apt:
    name:
      - fontconfig
      - fonts-noto-color-emoji
    state: present
  become: true

- name: "Fonts | Download nerd-fonts"
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip
    dest: "{{ ansible_user_dir }}/Meslo.zip"
  notify:
    - "Fonts | Cleanup downloaded zip file"

- name: "Fonts | Create fonts directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/fonts"
    state: directory
    mode: "0755"

- name: "Fonts | Unzip nerd-fonts"
  ansible.builtin.unarchive:
    src: "{{ ansible_user_dir }}/Meslo.zip"
    dest: "{{ ansible_user_dir }}/.local/share/fonts"
    remote_src: true

- name: "Fonts | Ensure config directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_user_dir }}/dev_env/.config/fontconfig"
    - "{{ ansible_user_dir }}/dev_env/.config/fontconfig/conf.d"

- name: "Fonts | Copy fontconfig file"
  ansible.builtin.copy:
    src: "fonts.conf"
    dest: "{{ ansible_user_dir }}/dev_env/.config/fontconfig/fonts.conf"
    mode: "0644"

- name: "Fonts | Copy emoji fontconfig file"
  ansible.builtin.copy:
    src: "01-emoji.conf"
    dest: "{{ ansible_user_dir }}/dev_env/.config/fontconfig/conf.d/01-emoji.conf"
    mode: "0644"

- name: "Fonts | Update font cache"
  ansible.builtin.shell: "fc-cache -fv"
  changed_when: false
